### ISSUE TITLE
Getting a 404: The requested URL was not found on the server.

### ISSUE THREAD

**Issue by shivams** [freedmand/semantra#77] opened 2024-05-09 16:57 UTC
I am trying to use Semantra for the first time. I did the setup and everything correctly. But when I finally run semantra using command: `semantra *.txt --host 0.0.0.0`, I am unable to open it on my browser (either from localhost or from a different machine). It throws 404 in both cases. I can see `404` message on the Flask app as well. What's going on? Am I missing something?

**Comment by shivams** [comment] 2024-05-09 17:43
@freedmand You mean it works in a "virtual pip environment"? I just tried that as well, but it gave the same error.

**Comment by freedmand** [comment] 2024-05-10 04:10
I just realized the issue is likely the way I bundled the latest version
without building the frontend first. I can get this patched tomorrow. In
the meantime, if you revert to the previous version (0.1.8) it should work.

**Comment by freedmand** [comment] 2024-05-10 17:36
This should be fixed now in version 0.1.10! Try updating and re-open if the problem persists. Thank you!

**Closed by freedmand** 2024-05-10 17:36 UTC
